export const dinerConstants = {
	GETALL_REQUEST: 'DINER_GETALL_REQUEST',
	GETALL_SUCCESS: 'DINER_GETALL_SUCCESS',
	GETALL_FAILED: 'DINER_GETALL_FAILED',

	POST_REQUEST: 'DINER_POST_REQUEST',
	POST_SUCCESS: 'DINER_POST_SUCCESS',
	POST_FAILED: 'DINER_POST_FAILED',

	DELETE_REQUEST: 'DINER_DELETE_REQUEST',
	DELETE_SUCCESS: 'DINER_DELETE_SUCCESS',
	DELETE_FAILURE: 'DINER_DELETE_FAILURE'
};
