export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

// waiting for the promise to return
export const REQUEST_RESTAURANTS_PENDING = 'REQUEST_RESTAURANTS_PENDING';
export const REQUEST_RESTAURANTS_SUCCESS = 'REQUEST_RESTAURANTS_SUCCESS';
export const REQUEST_RESTAURANTS_FAILED = 'REQUEST_RESTAURANTS_FAILED';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_ROUTE_HOME = 'CHANGE_ROUTE_HOME';
export const CHANGE_ROUTE_SIGNUP = 'CHANGE_ROUTE_SIGNUP';
export const CHANGE_ROUTE_SIGNIN = 'CHANGE_ROUTE_SIGNIN';
export const POST_SIGNINFO_EMAIL = 'POST_SIGNINFO_EMAIL';
export const POST_SIGNINFO_PASSWORD = 'POST_SIGNINFO_PASSWORD';
export const POST_SIGNINFO_NAME = 'POST_SIGNINFO_NAME';
export const POST_SIGNINFO_LOGINSTATUS = 'POST_SIGNINFO_LOGINSTATUS';

// route constants
export const HOME = 'HOME';
export const SIGNUP = 'SIGNUP';
export const SIGNIN = 'SIGNIN';
