export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

// waiting for the promise to return
export const REQUEST_RESTAURANTS_PENDING = 'REQUEST_RESTAURANTS_PENDING';
export const REQUEST_RESTAURANTS_SUCCESS = 'REQUEST_RESTAURANTS_SUCCESS';
export const REQUEST_RESTAURANTS_FAILED = 'REQUEST_RESTAURANTS_FAILED';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
